apiVersion: v1
kind: Service
metadata:
  name: {{ include "ping-pong.fullname" . }}
  labels:
    {{- include "ping-pong.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ default .Values.service.port .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "ping-pong.selectorLabels" . | nindent 4 }}
